version: '2.1'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE=postgres
      - LOGLEVEL=crit
      - NODE_ENV=test
      - POSTGRES_DATABASE=jellyfish
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - MAIL_TYPE=mailgun
      - MAILGUN_DOMAIN=mail.ly.fish
      - MAILGUN_BASE_URL=https://api.mailgun.net/v3
      - MAILGUN_TOKEN
      - INTEGRATION_DEFAULT_USER=admin
      - INTEGRATION_GOOGLE_MEET_CREDENTIALS={}
      - CI=1
      - NPM_TOKEN
    networks:
      - internal
