version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_google_meet_credentials
      - mailgun_token
    networks:
      - internal

secrets:
  integration_google_meet_credentials:
    file: ./.balena/secrets/integration_google_meet_credentials
  mailgun_token:
    file: ./.balena/secrets/mailgun_token
