# This file is auto-synced from product-os/jellyfish-config/sync/docker-compose.test.yml
# and should only be edited there!

version: '2.1'

services:
  sut:
    image: balena/jellyfish-action-library_sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE=postgres
      - LOGLEVEL=crit
      - NODE_ENV=test
      - POSTGRES_DATABASE=jellyfish
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
    env_file:
      - test.env
    secrets:
      - integration_google_meet_credentials
    networks:
      - internal

secrets:
  integration_google_meet_credentials:
    file: ./.balena/secrets/integration_google_meet_credentials.txt

