version: '3'

env:
  INTEGRATION_GOOGLE_MEET_CREDENTIALS:
    sh: cat /run/secrets/integration_google_meet_credentials
  MAILGUN_TOKEN:
    sh: cat /run/secrets/mailgun_token

tasks:
  test:
    cmds:
      - npm run test:integration
